### ISSUE TITLE
Make Blueprint entries correspond to initialization kwargs for basic C-Star classes

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/C-Star#100]
Currently, `list(blueprint_dict["components"][idx].keys())` would be `[base_model, discretization, additional_code, input_datasets]`, each of which corresponds to one of C-Star's lowest level classes. The entry under each of these should be a dict that can be directly used to create an instance of that class, e.g. : `example = AdditionalCode(**blueprint_dict["components"][idx]['additional_code'])`

Following #97 , This will already be the case for all of these classes except, I believe, `BaseModel`, which has a `name` entry in the blueprint which is not used to create a `BaseModel` object.

This `name` entry should be maintained, as it is used by C-Star to make certain decisions. I proposed it is moved to the (component) level of the others: `[name, base_model, discretization, additional_code, input_datasets]`

It is impossible to instantiate a Component object directly from the dictionary at this level without first parsing the nested dictionaries anyway, and all instances of C-Star using `base_model.name` this way are in the context of decisions at the component level, so this feels appropriate.

**Comment by TomNicholas** [comment]
Yes great! I was going to suggest something similar.
