### ISSUE TITLE
establish pre-commit, codecov, etc.

### ISSUE THREAD

**Issue by matt-long** [CWorthy-ocean/C-Star#11]
we should setup `pre-commit` for syntax checking and testing

This repo is the last time I worked on this:
https://github.com/marbl-ecosys/feisty

Perhaps @TomNicholas can provide an updated example?

**Comment by NoraLoose** [comment]
- [x] We have linked C-Star to `codecov`.
- [ ] I'm working on setting up `pre-commit`, see #68
