### ISSUE TITLE
re-run doc examples after roms-tools fix

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/C-Star#137]
see: https://github.com/CWorthy-ocean/roms-tools/issues/163

**Comment by NoraLoose** [comment]
Can be addressed now. And probably should before testing starts?

**Comment by NoraLoose** [comment]
roms-tools v.1.4.1 (available on PyPI) contains the fixes

**Comment by dafyddstephenson** [comment]
Will take this on when at a workstation this afternoon, thanks for the update.

**Comment by NoraLoose** [comment]
When you re-run [this notebook](https://c-star.readthedocs.io/en/latest/3_restarting_and_continuing_a_case.html), do you mind changing the following things in the final notebook cell:
* Add a comment
```
BGC_DS = xr.open_dataset(example_case_2.caseroot / 'output/ROMS_MARBL_bgc.20120103120000.nc')  # this contains 6-hourly data, with the date in the filename reflecting the first time entry
```
* Use lower-case `cmap` in 
```
p2 = ax2.pcolormesh(lon,lat,BGC_DA.isel(time=0).values, vmin=VMIN, vmax=VMAX, cmap=cmap)
p3 = ax3.pcolormesh(lon,lat,BGC_DA.isel(time=-1).values, vmin=VMIN, vmax=VMAX, cmap=cmap)
```

**Comment by NoraLoose** [comment]
When re-running [this notebook](https://c-star.readthedocs.io/en/latest/2_importing_and_running_a_case.html), you could also change the colorbar bounds so that they are based on the mask rather than doing
```
vmin = min(ini_data.where(ini_data!=0).min(), rst_data.where(rst_data!=0).min())
vmax = max(ini_data.where(ini_data!=0).max(), rst_data.where(rst_data!=0).max())
```

**Comment by dafyddstephenson** [comment]
yep good point!
