### ISSUE TITLE
Static installation of `C-Star` fails

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/C-Star#147]
Our internal tester @ubbu36 has found the first bug!

Installing C-Star statically via
```
pip install .
```
seems to lead to an incomplete installation of C-Star. Typing
```
import cstar
```
leads to the follwing error
```
ModuleNotFoundError: No module named 'cstar.base'
```

Installing C-Star dynamically (which is what the developers have done) via
```
pip install -e .
```
works fine.

**Comment by TomNicholas** [comment]
I can't seem to reproduce this locally, but if anyone can, some possible culprits:

- [ ] The `pyproject.toml` is slightly different to others I've looked at, ours includes the lines
    
    ```
    # Automatically find the packages
    where = ["."]
    include = ["cstar"]
    ```
    
    which we might want to try removing

- [ ] There needs to be a `__init__.py` file in every directory that contains any python code that could be imported, but there appear to be some missing from the test file directories (`unit_tests`)
