### ISSUE TITLE
Pull request template is not being used

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/C-Star#197]
The [PULL_RELEASE_TEMPLATE.md](https://github.com/CWorthy-ocean/C-Star/blob/main/.github/PULL_RELEASE_TEMPLATE.md) is not being used when a new PR is opened.

I think we have to rename `PULL_RELEASE_TEMPLATE.md` --> `pull_request_template.md` to solve this issue.

**Comment by TomNicholas** [comment]
that's because it says "release" not "request". [This one in VirtualiZarr works](https://github.com/zarr-developers/VirtualiZarr/blob/main/.github/PULL_REQUEST_TEMPLATE.md), because the filename is `PULL_REQUEST_TEMPLATE.md`
