### ISSUE TITLE
Clean up repository & move python package to top level

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/C-Star#2]
Move the `setup_tools` and `setup_cstar` directories to their own repositories (ideally maintaining their commit histories there), move the contents of `cstar_ocean` to the repo top level, and run a repo cleaner to remove traces of `setup_tools` and possibly  `setup_cstar`. 

EDIT: The total C-Star repo size is 1.1GB, of which only 250kB is the python package, which we'd like to be the exclusive project in the repo going forward. Cleaning out these other projects from the history is therefore necessary.

`setup_cstar` here is the script-based precursor to C-Star, which has a small user base and allows those with interest to set up ROMS-MARBL with a single line of code. I am happy to continue maintaining it in a separate repository.

**Comment by dafyddstephenson** [comment]
@matt-long @aliciak-cworthy @sdbachman @TomNicholas @NoraLoose please read, thanks!

I have created three new repos from the individual projects in the C-Star repo, each with its relevant commit history intact (though the hashes have changed). 
Currently nothing has changed in the original C-Star repo.
New repos:

- `matlab_setup_tools` ([here](https://github.com/CWorthy-ocean/matlab_setup_tools) ; I have transferred ownership of this to [C]Worthy)
- `cstar_bash`: this is the script-based version that does appear to have a limited user base and would be a low lift to maintain. If we can decide a more appropriate name for the repo I can rename it and transfer ownership to [C]Worthy. EDIT 2024-08-01: [done](https://github.com/CWorthy-ocean/roms_marbl_setup_assistant).
- `cstar_python` (Currently on my account [here](https://github.com/dafyddstephenson/cstar_python)).
 
I propose adding the C-Star remote to `cstar_python` and force pushing to overwrite [the original contents of C-Star](https://github.com/CWorthy-ocean/C-Star) with it. I will keep a local copy of the old C-Star repo as a backup **but this is a very destructive change and I'd like to have it reviewed/approved first please!**. Issues and PRs will stay intact, but commit hashes in the history will change. Creating a PR about this would be messy and I don't know if it's even possible? so perhaps we can discuss here.

Steps taken:
- clone a fresh copy of C-Star to my laptop, with `ROMS_setup_instructions`, `setup_tools`, `setup_cstar`, `cstar_ocean` directories
- use e.g. `git filter-repo --path ROMS_setup_instructions --path setup_tools` to strip out all files and commits not connected to these two directories
- Create a new repo e.g. `matlab_setup_tools` on GitHub and add this as the remote of the filtered local copy of C-Star
- push to the new repo

(rinse and repeat for other directories)

Thanks!

**Comment by TomNicholas** [comment]
> I have created three new repos from the individual projects in the C-Star repo

I support separating out individual projects rather than having one repo be a catch-all.

> `cstar_bash` (Currently on my account [here](https://github.com/dafyddstephenson/cstar_bash)): this is the script-based version that does appear to have a limited user base

It's unclear to me what `cstar_bash` actually is - have you mentioned this before? Why would we need a bash version of anything when the point of `cstar` is to be a python package with a command-line interface?

> I propose adding the C-Star remote to cstar_python and force pushing to overwrite [the original contents of C-Star](https://github.com/CWorthy-ocean/C-Star) with it

I don't really understand why this is necessary - what's wrong with just making new commits to this repository to delete the now-outdated content that you want to move to other new repos?

**Comment by dafyddstephenson** [comment]
> It's unclear to me what `cstar_bash` actually is - have you mentioned this before? Why would we need a bash version of anything when the point of `cstar` is to be a python package with a command-line interface?

This is the shell script-based precursor to C-Star. To be clear, I think the name "C-Star" should be dropped from this, but it has value independently of C-Star. there's been a lot of interest in ROMS-MARBL and this code effectively converts the entire setup process of ROMS-MARBL from a convoluted series of steps into a one-liner. Issue CWorthy-ocean/C-Star#25  refers to this project, and I have also received emails from people using it.

> > I propose adding the C-Star remote to cstar_python and force pushing to overwrite [the original contents of C-Star](https://github.com/CWorthy-ocean/C-Star) with it
> 
> I don't really understand why this is necessary - what's wrong with just making new commits to this repository to delete the now-outdated content that you want to move to other new repos?

Apologies, I thought I wrote this in the original issue (now edited) but the C-Star repo is 1.1GB, of which only 250kB is the python package. This issue was the primary motivator behind the split.

**Comment by TomNicholas** [comment]
> This is the shell script-based precursor to C-Star. To be clear, I think the name "C-Star" should be dropped from this, but it has value independently of C-Star. there's been a lot of interest in ROMS-MARBL and this code effectively converts the entire setup process of ROMS-MARBL from a convoluted series of steps into a one-liner. Issue https://github.com/CWorthy-ocean/C-Star/issues/25 refers to this project, and I have also received emails from people using it.

Okay! Sounds like this is useful, but you might want to consider whether or not to actually maintain it (as opposed to e.g. archiving it and pointing people to the python C-Star instead).

> Apologies, I thought I wrote this in the original issue (now edited) but the C-Star repo is 1.1GB, of which only 250kB is the python package. This issue was the primary motivator behind the split.

Okay gotcha, thanks for explaining. That makes more sense - some kind of deep git hackery has to be done to get rid of all that old data.

>  force pushing to overwrite

I think this sounds okay to me. It would mean anyone else who has forked the repo in the past will have to rebase, but that's an argument for doing this asap.

**Comment by NoraLoose** [comment]
Re the shell script-based precursor to C-Star (`cstar_bash`): Given what I heard from @dafyddstephenson, `cstar_bash` already has a user base consisting of a handful people. Also, from what I understand, `cstar_bash` allows more user control and is less black-boxy than the python package. So more advanced users may be interested in using it in the future. All that to say I think it's worth keeping it in a separate repo, as Dafydd is suggesting. Not sure how much work it would be to maintain it, Dafydd?

👍 from me for the deep clean of the existing C-Star repo. Dafydd, your plan looks good to me, and as long as we have the current C-Star on a fork as a backup, I'm not too nervous. :)

**Comment by dafyddstephenson** [comment]
As an update, I have continued working on some enhancements to C-Star in the background (PR CWorthy-ocean/C-Star#35 ) and think these have grown to the point where they would be best merged in first. 

I have also renamed `cstar_bash` to [`roms_marbl_setup_assistant`](https://github.com/CWorthy-ocean/roms_marbl_setup_assistant) to make sure it is considered a separate thing from C-Star, and have transferred ownership to [C]Worthy, so now both other projects have new homes on the [C]Worthy GitHub account.

Have confirmed in person with @aliciak-cworthy that she's happy to go ahead with deep cleaning those two projects out of here and rewriting the commit history, just waiting to check all this looks ok to @matt-long and @sdbachman .

**Comment by dafyddstephenson** [comment]
Alright everybody, welcome to the new repo! The old one is at https://github.com/CWorthy-ocean/C-Star_ARCHIVE.
I've transferred all the issues etc. over here.
