### ISSUE TITLE
ls command in example notebook assumes you are Daffydd!

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/C-Star#22]
This cell in the example notebook obviously doesn't work on my machine:

`ls /Users/dafyddstephenson/Code/my_c_star/cstar_ocean/roms_marbl_example_cstar_case/output/`

**Comment by TomNicholas** [comment]
In my case this worked `ls ./roms_marbl_example_cstar_case/output/`, but I'm not sure we can assume we know where the notebook is being run from? This is something that we could solve with pathlib I think.

**Comment by dafyddstephenson** [comment]
nice catch - we can use the caseroot variable
