### ISSUE TITLE
Redundancy of public `exists_locally` vs `check_exists_locally`

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/C-Star#25]
I feel like we don't need two public methods that do basically the same thing. Instead we might just have one read-only property `exists_locally` which internally calls a private method `_check_exists_locally`.

**Comment by dafyddstephenson** [comment]
Is the suggestion here just to rename `check_exists_locally` to indicate it's non-public? 

There is a broader issue here in that `exists_locally` can't be set at init by a call to `check_exists_locally`, as the latter takes a path as an argument to determine where to look, and until `InputDataset.get(tgt_path)` has been called, it's unclear where to check for local existence. 

When called from within `Case.check_is_setup`, it is clear what path to provide to `InputDataset.check_exists_locally` based on `Case.caseroot` .
