### ISSUE TITLE
Integrate ROMS tools

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/C-Star#3]
For the `InputDataset` class, we should support the ability for the `source` attribute to point not only to a pre-created netcdf file containing the dataset, but also a yaml file containing instructions for _creating_ the dataset with [ROMS-tools](https://github.com/CWorthy-ocean/roms-tools). The `file_hash` attribute could still be used to verify that the created file is identical to the one that would be sourced remotely.

Related issue: [roms-tools # 63](https://github.com/CWorthy-ocean/roms-tools/issues/63)

**Comment by NoraLoose** [comment]
@dafyddstephenson I just merged a PR that adds yaml recipes to `ROMS-Tools` (https://github.com/CWorthy-ocean/roms-tools/pull/64). Obviously, I still have to work on "steps 7-10", but maybe we can already start the integration process and see if I need to change anything about the `.to_yaml` and `.from_yaml` methods on the `ROMS-Tools` side.

EDIT: I also published a new release of `ROMS-Tools` that includes the yaml recipes, in case you want to install from pip and give it a spin.
