### ISSUE TITLE
Tools for diff-ing and sanitizing notebooks

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/C-Star#37]
Using git with jupyter notebooks is notoriously a bit annoying. There are some tools intended to make this easier however, such as [ReviewNB](https://www.reviewnb.com/). If we're making lots of alterations to notebooks we might want to use these tools.

**Comment by NoraLoose** [comment]
I added ReviewNB to the C-Star and ROMS-Tools repo. It is working for the ROMS-Tools repo (see, e.g., https://github.com/CWorthy-ocean/roms-tools/pull/98#issuecomment-2310799692), so I think it will work here, too. I'm not closing this issue yet until we make changes to notebooks and confirm functionality.

**Comment by dafyddstephenson** [comment]
Seems to work pretty well for my last couple of PRs - thanks Nora! This is cool. good to close?

**Comment by NoraLoose** [comment]
Glad to hear this is working. I'm closing this issue.
