### ISSUE TITLE
support local paths to input datasets

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/C-Star#4]
Currently the `source` attribute on `Inputdataset` only supports URLs to remotely hosted files, while `AdditionalCode` is described by a `source_repo`. We should support `source` strings that are local paths.

**Comment by TomNicholas** [comment]
> URLs to remotely hosted files

Github URLs? Or S3 urls? It's relevant for the idea of using `cloudpathlib` everywhere (see https://github.com/CWorthy-ocean/cstar_new/issues/9)

**Comment by dafyddstephenson** [comment]
Not strictly either, anything pooch can fetch - CWorthy-ocean/cstar_new#9 definitely seems relevant here though
