### ISSUE TITLE
Pre-commit

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/C-Star#68]
We want to take advantage of `pre-commit` in two ways beyond what it's doing now in the C-Star repo:

- [ ]  Include it in the CI
- [ ]  Let it format the docstrings correctly for us (e.g., via `docformatter` or `pdocstyle`) because the docstrings are not showing up correctly in the documentation, see all these warnings

![Screenshot 2024-09-04 at 2 37 35 PM](https://github.com/user-attachments/assets/ff97bb52-6e68-4b36-beed-915d41f80eea)

**Comment by dafyddstephenson** [comment]
I think this one is covered by #11  ?

**Comment by NoraLoose** [comment]
This issue should be re-opened as outlined in #80
