### ISSUE TITLE
Module naming conventions

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/C-Star#7]
> the `cstar_*` prefixes here are unnecessary, we should change the names of the modules to be short and simple, e.g. `cstar.base`, `cstar.inputs`.

_Originally posted by @TomNicholas in https://github.com/CWorthy-ocean/C-Star/pull/24#discussion_r1673048712_

**Comment by TomNicholas** [comment]
Also can I just say that calling anything `CStar-Ocean` is a tautology - at least if "CSTAR" is vaguely a backcronym for "Computational System for Tracking Ocean Carbon". `-Ocean` is also redundant if CWorthy never has plans to track anything that's not in the ocean!

**Comment by NoraLoose** [comment]
@TomNicholas Yesterday, we talked about moving everything from the subdirectory `cstar_ocean` into the main level repo `C-Star`. So there won't be any `-ocean` suffix anymore!

**Comment by TomNicholas** [comment]
Great! I'll close this once that has been done then.

**Comment by NoraLoose** [comment]
It will happen as part of the next PR, so not quite done yet. The same PR will do a deep cleaning of all the other subdirectories that are part of `C-Star` right now (matlab tools etc.). Sounded like a good idea to have this in a separate PR to minimize messiness.

**Comment by dafyddstephenson** [comment]
I'll add that the "ocean" suffix was added by Matt very early on as there is already a python package named `cstar` (and furthermore that the acronym has since been abandoned and so the tautology issue is avoided)

**Comment by TomNicholas** [comment]
>  there is already a python package named cstar

That's a concern for what we name the package in PyPI and conda-forge, but it doesn't matter for what we name in the package in the user code because no-one is likely to be trying to import our `cstar` package alongside that existing `cstar` package.

**Comment by TomNicholas** [comment]
To be clear - the use of underscores, whilst allowed, is explicitly discouraged in official python style guides (see https://stackoverflow.com/a/2852305).

Sounds like we do need to use an underscore in the PyPI package name, but I think we should try to avoid using them anywhere else.
