### ISSUE TITLE
Redirect subprocess output

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/C-Star#76]
There is currently a lot of output associated with compilation, execution etc. that buries any print statements from C-Star, has caused issues with our Jupyter notebooks, and is just generally ugly. Most users will not want to see this output. Most of the processes responsible are called by `subprocess`, which provides simple functionality for redirecting output to files.

We should have a `<caseroot>/logs` directory that categorises and stores subprocess output, and C-Star should provide hints to advanced users about where they can find such output if they have a morbid interest in looking at thousands of compiler warnings about ROMS.

**Comment by TomNicholas** [comment]
There are existing tools for logging (python has a logging module for example) that we should look at before implementing this.
