### ISSUE TITLE
Testing ROMS-Tools <-> C-Star integration in CI

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/C-Star#77]
We should test the ROMS-Tools integration in the CI. And should ROMS-Tools be a (required or optional) dependency of C-Star as defined in `pyproject.toml`?

**Comment by TomNicholas** [comment]
In theory it's optional, at least in the same theoretical sense in which C-Star could support oceananigans.

**Comment by dafyddstephenson** [comment]
I think for alpha we should treat it as a dependency and make an issue to untangle them. My roms-tools integration PR will include a test (in the old format for now, sorry! I will take some time to study the pytest reformulation once it's in).
