### ISSUE TITLE
Issues with linting CI

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/C-Star#80]
1. I'm not convinced that the formatting linter is running correctly,
2. There is no separate test in the CI for pre-commit

**Comment by TomNicholas** [comment]
roms-tools looks good, so lets just copy the configuration from there.

**Comment by dafyddstephenson** [comment]
There is now a separate CI section for pre-commit! (somewhere in the PR line). Also we found out this week roms-tools isn't using mypy, so C-Star linting is stricter.

**Comment by dafyddstephenson** [comment]
> There is now a separate CI section for pre-commit! (somewhere in the PR line).

Strike that, it's already in. In that case I'm not sure I understand the issue.

**Comment by TomNicholas** [comment]
In https://github.com/CWorthy-ocean/C-Star/pull/71#discussion_r1759660634 I pulled down your PR branch, which was passing all green in the CI. I immediately ran `pre-commit` on it locally, and `ruff` found a bunch of formatting to fix (applied in https://github.com/CWorthy-ocean/C-Star/pull/71/commits/9442114fb69e83856a85240c90bb5b235334697e). This shouldn't have been possible if everything is working correctly - the PR should have had a red failure. Beyond that I'm not exactly sure what is wrong yet.

**Comment by TomNicholas** [comment]
> > There is now a separate CI section for pre-commit! (somewhere in the PR line).
>
> Strike that, it's already in. In that case I'm not sure I understand the issue.

I want it to look more like [this](https://github.com/CWorthy-ocean/roms-tools/pull/128), with an explicit extra CI job just for pre-commit (and ideally another one for mypy)

<img width="944" alt="Screenshot 2024-09-14 at 12 05 22 AM" src="https://github.com/user-attachments/assets/afa735bc-e4b2-4bf2-be65-9e9891539ce5">

**Comment by TomNicholas** [comment]
#81 is an example of what I'm talking about - the CI makes it look like tests are failing, when it's actually just a mypy error (much less of a big deal).

**Comment by NoraLoose** [comment]
That is annoying. Let me issue a quick PR that separates out the pre-commit stuff from the tests.
