### ISSUE TITLE
Issues with pre-commit on Perlmutter

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/C-Star#92]
I can't run `pre-commit` on the `C-Star` repo on Perlmutter. There is an error related to file locking:
```
[INFO] Locking pre-commit directory
An unexpected error has occurred: OSError: [Errno 524] Unknown error 524
Traceback (most recent call last):
  File "/global/homes/n/nloose/.conda/envs/cstar_env/lib/python3.12/site-packages/pre_commit/file_lock.py", line 58, in _locked
    fcntl.flock(fileno, fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 524] Unknown error 524
```

**Comment by NoraLoose** [comment]
This is maybe unrelated (but maybe not): If I run `pre-commit` on my local machine I get a warning:
```
[WARNING] Unexpected key(s) present on https://github.com/pre-commit/pre-commit-hooks: files
```

**Comment by dafyddstephenson** [comment]
The `files` key can go, I can take a look at the perlmutter issue if that doesn't help!

**Comment by NoraLoose** [comment]
Removing the `files` key did not solve the problem. But solving this issue is not highest priority IMO.

**Comment by NoraLoose** [comment]
I have the same problem with `ROMS-Tools`, so this issue is not `C-Star` specific.

**Comment by NoraLoose** [comment]
This is now solved, apparently after Perlmutter's 3-day maintenance.
